-- Checklist entries (daily workout diary)
create table if not exists public.checklist_entries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  day_number int not null,
  back_pain int not null check (back_pain between 0 and 3),
  kps_feeling int not null check (kps_feeling between 1 and 3),
  left_knee int not null check (left_knee between 0 and 2),
  sitting_symmetry text not null check (sitting_symmetry in ('да', 'чуть меньше', 'примерно ровно'))
);

alter table public.checklist_entries enable row level security;
create policy "anon read" on public.checklist_entries for select using (true);
create policy "anon insert" on public.checklist_entries for insert with check (true);

-- Analysis reports (generated by /analyze-results)
create table if not exists public.analysis_reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  report_date date not null,
  entries_count int not null,
  period_start date not null,
  period_end date not null,
  content text not null,
  recommendation text not null check (recommendation in ('ok', 'warning', 'critical'))
);

alter table public.analysis_reports enable row level security;
create policy "anon read" on public.analysis_reports for select using (true);
create policy "anon insert" on public.analysis_reports for insert with check (true);
