-- Gym set log entries (per-workout diary, sets logged as jsonb)
create table if not exists public.gym_entries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  workout_number int not null,
  rpe text not null check (rpe in ('Легко', 'Норм', 'Тяжело', 'Предел')),
  knee_pain int not null check (knee_pain between 0 and 2),
  sets jsonb not null,
  comment text
);

alter table public.gym_entries enable row level security;
create policy "anon read" on public.gym_entries for select using (true);
create policy "anon insert" on public.gym_entries for insert with check (true);

-- Gym analysis reports (generated by /gym-analyze-results)
create table if not exists public.gym_analysis_reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  report_date date not null,
  entries_count int not null,
  period_start date not null,
  period_end date not null,
  content text not null,
  recommendation text not null check (recommendation in ('ok', 'warning', 'critical'))
);

alter table public.gym_analysis_reports enable row level security;
create policy "anon read" on public.gym_analysis_reports for select using (true);
create policy "anon insert" on public.gym_analysis_reports for insert with check (true);
